### ISSUE TITLE
ERROR - No virtual method startForegroundService

### ISSUE THREAD

**Issue by aktivdigital-frontend** [angeloraso/capacitor-plugin-background-mode#5]
Hi!

I got an error, after I enabled background mode. Could you help, please?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: APPID, PID: 2836
    java.lang.NoSuchMethodError: No virtual method startForegroundService(Landroid/content/Intent;)Landroid/content/ComponentName; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
        at com.angeloraso.plugins.backgroundmode.BackgroundMode.startService(BackgroundMode.java:144)
        at com.angeloraso.plugins.backgroundmode.BackgroundMode.onStop(BackgroundMode.java:77)
        at com.angeloraso.plugins.backgroundmode.BackgroundModePlugin.handleOnStop(BackgroundModePlugin.java:54)
        at com.getcapacitor.Bridge.onStop(Bridge.java:1277)
        at com.getcapacitor.BridgeActivity.onStop(BridgeActivity.java:106)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
        at android.app.Activity.performStop(Activity.java:7168)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4238)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4290)
        at android.app.ActivityThread.-wrap28(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
        
        
Ionic:

   Ionic CLI                     : 6.20.4 (C:\Users\AKTIVD~1\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.5.6
   @angular-devkit/build-angular : 15.2.0
   @angular-devkit/schematics    : 15.2.0
   @angular/cli                  : 15.2.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

**Comment by angeloraso** [comment]
Hi [aktivdigital-frontend](https://github.com/aktivdigital-frontend) 
I can't reproduce your problem but it seems that the "startForegroundService" method doesn't exist in the "mcontext" object, which doesn't make much sense.
Could the application context obtained be the wrong one? It's weird but it's all I can think of.
Do you have steps to reproduce the issue or does it happen randomly?
